name: ci

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Permissions
        run: chmod +x ./deploy.sh
      - name: Deploy
        run: ./deploy.sh
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          KUBECTL_CONFIG: ${{ secrets.KUBECTL_CONFIG }}
          BUILD_NUMBER: ${{ github.run_number }}